name = "web-message"
main = "src/index.js"
compatibility_date = "2024-01-01"
[[d1_databases]]
binding = "DB"
database_name = "message-board-db"
database_id = "cadc7c30-de75-4a78-9c33-bc292ac74b48"  
[[rules]]
type = "Text"
globs = ["**/*.html"]
